import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";

export default function Home() {
    return (
        <>
            <Head>
                <title>william | Home Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main className="flex items-center text-datk w-full min-h-screen">
                <Layout className="pt-0 md:pt-16 sm:pt-8">
                    <div className="flex items-center justify-between w-full lg:flex-col">
                        <div className="w-1/2 md:w-full">
                            <Image
                                src="/images/profile/ProfilePic.png"
                                alt="my profile picture"
                                className="w-full h-auto lg:hidden md:inline-block md:w-full md:pb-[30px]"
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                                priority
                                width={500}
                                height={500}
                            />
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="Turn big ideas into real things using coding and designing."
                                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text 6xl md:!text-5xl sm:!text-3xl"
                            />
                            <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                                {"Hi, I&apos;m Ness Watson Tangsang  a frontend developer passionate about building beautiful, responsive, and user friendly websites. I specialize in JavaScript, React, and Next.js, Figma, Firebase and I&apos;m always eager to learn new tools and techniques to grow as a developer. As a dedicated learner, I&apos;m excited to apply my skills to real world projects and collaborate with talented individuals to create impactful digital experiences."}
                            </p>
                            <div className=" w-80 flex justify-between items-center self-start mt-2 lg:self-center">
                                <Link
                                    href="/NESS RESUME update.pdf" //"Resume-light.pdf"
                                    target={"_blank"}
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg front-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                                    download={true}
                                >
                                    Resume
                                    <LinkArrow className={"w-6 ml-1"} />
                                </Link>
                                <Link
                                    href="mailto:william.sinclair92@gmail.com"
                                    target={"_blank"}
                                    className="ml-4 font-medium capitalize text-dark underline border-2 border-solid border-transparent hover:border-dark rounded-lg text-lg front-semibold p-2.5 px-6 md:text-base"
                                >
                                    Contact
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <Hireme />
            </main>
        </>
    );
}
